update information for insyde
HypsyNZ/DSEDodge-Signed-Kernel-Driver pull request #1
Opened 2022-08-31 11:18 UTC by eebssk1

2022-08-31 11:41 UTC, HypsyNZ requested changes

2022-08-31 11:41 UTC, HypsyNZ commented on README.md
> +Click okay and then "Exit saving changes" in the bottom.
> then "Exit saving changes" 

I'm going to need to see proof that this doesn't brick your motherboard (video)

2022-08-31 11:41 UTC, HypsyNZ commented on README.md
> +Click "Administrate Secure Boot" in the main menu.
Can you provide a screenshot of all the menus you mention

2022-08-31 11:41 UTC, HypsyNZ commented on README.md
> +When it asks about Owner GUID, you can use anyone you like, just keep sure it's same across your cer files.
Please elaborate on this

2022-08-31 12:47 UTC, eebssk1 commented on README.md
> +Click "Administrate Secure Boot" in the main menu.
hold on

2022-08-31 12:49 UTC, eebssk1 commented on README.md
> +When it asks about Owner GUID, you can use anyone you like, just keep sure it's same across your cer files.
it's actually showed in your step 5 screenshot. But insyde is too lazy to generate for you and some oem preinstalled their cert may have different owner GUID.
https://techlibrary.hpe.com/docs/iss/proliant-gen10-uefi/GUID-E4427875-D123-4BBF-9056-342168478A02.html

2022-09-01 03:31 UTC, closed without merging

2022-09-01 03:32 UTC, HypsyNZ commented
Please add more detailed instructions or explain how this pull request adds new information, please don't send links.

2022-09-01 07:21 UTC, eebssk1 commented
Tested. Unfortunately, this does not work on my device. >_<